### PR TITLE
Optimized encoding and decoding; simplified API

### PR DESCRIPTION
**Pull request by ChaiTRex**
# Improvements

* Encoding slightly faster and decoding much faster
* Encoding now appends to the given `String`, which is useful and which avoids the old behavior of just pointing the `String` reference at a completely new `String`, which is a usually-unnecessary allocation; if desired, the `String`'s contents can be replaced instead of appended to by `clear`ing the `String` before calling the encoding functions
* New `digit_count` function used to preallocate space in `String`s when encoding
* `Flavor` enum eliminated in favor of duplicated functions; this simplifies the API quite a bit
* Improved documentation, including examples that are true doctests (`assert_eq!` instead of `println!`)
* Added new `must_use`s and included the reason why the value must be used
* `DecodeError`'s `Debug` implementation now follows standard practice of producing a source code-like version of the error
* `DecodeError`'s invalid byte variant now stores a `u8` and now shows the `u8` in `b'_'` form when `Display` is used
* Renamed base62 variants to 'standard' and 'alternative'
* Simplified module structure by moving `base62` module to become the root of the crate

---

# Benchmarks

### Old

    encode                  time:   [536.18 ns 537.69 ns 539.22 ns]
    Found 1 outliers among 100 measurements (1.00%)
      1 (1.00%) high mild

### New

    encode                  time:   [502.33 ns 503.82 ns 505.46 ns]
    Found 1 outliers among 100 measurements (1.00%)
      1 (1.00%) high severe
    
### Old

    encode_reversed         time:   [530.70 ns 532.18 ns 533.59 ns]
    Found 1 outliers among 100 measurements (1.00%)
      1 (1.00%) high mild

### New

    encode_alternative      time:   [499.17 ns 500.06 ns 501.01 ns]

### Old

    decode                  time:   [340.28 ns 341.31 ns 342.40 ns]

### New

    decode                  time:   [59.846 ns 60.068 ns 60.290 ns]
    Found 2 outliers among 100 measurements (2.00%)
      1 (1.00%) low mild
      1 (1.00%) high severe

### Old

        decode_reversed         time:   [373.42 ns 376.42 ns 380.59 ns]
    Found 3 outliers among 100 measurements (3.00%)
      1 (1.00%) high mild
      2 (2.00%) high severe

### New

        decode_alternative      time:   [58.201 ns 58.353 ns 58.503 ns]
    Found 1 outliers among 100 measurements (1.00%)
      1 (1.00%) low mild

### CODE REVIEW

**Comment by ChaiTRex** [comment]
I only have a shared VPS, so benchmark times are a bit inexact for me. I have tried manually inlining and using `#[inline(…)]` hints and trying different refactorings and the newest commit is the best I was able to get.

    encode_standard_new     time:   [491.79 ns 493.08 ns 494.32 ns]
    Found 5 outliers among 100 measurements (5.00%)
      5 (5.00%) high mild
    
    encode_standard_buf     time:   [495.88 ns 496.85 ns 497.86 ns]
    
    encode_alternative_new  time:   [490.45 ns 491.59 ns 492.73 ns]
    
    encode_alternative_buf  time:   [498.27 ns 499.00 ns 499.78 ns]
    
    decode_standard         time:   [61.845 ns 62.681 ns 63.662 ns]                            
    Found 5 outliers among 100 measurements (5.00%)
      5 (5.00%) high severe
    
    decode_alternative      time:   [63.622 ns 63.769 ns 63.923 ns]
    Found 7 outliers among 100 measurements (7.00%)
      5 (5.00%) low mild
      1 (1.00%) high mild
      1 (1.00%) high severe

---

New changes:

* Long, repeated code snippets are moved to macros
* Refactoring made encoding functions about 10 to 15 ns faster
* `InvalidBase62Byte`'s `Display` implementation no longer allocates a `String`
* Added benchmarks for `encode_buf` and `encode_alternative_buf`
* Extended benchmark names so that none are prefixes of any others because `cargo bench prefix_of_benchmark_names` can be used to run only one benchmark, unless that benchmark's name is the prefix of another benchmark's name, which will cause it to run both

**Comment by ChaiTRex** [comment]
By using `u64` instead of `u128` division when possible, encoding is 3 times faster, decoding is slightly faster, and I assume but haven't measured that `digit_count` is faster.

    encode_standard_new     time:   [168.66 ns 169.25 ns 169.79 ns]
        
    encode_standard_buf     time:   [170.61 ns 171.21 ns 171.83 ns]
        
    encode_alternative_new  time:   [164.79 ns 165.56 ns 166.37 ns]
    Found 1 outliers among 100 measurements (1.00%)
      1 (1.00%) high mild
    
    encode_alternative_buf  time:   [171.31 ns 171.94 ns 172.60 ns]
    
    decode_standard         time:   [53.657 ns 53.839 ns 54.021 ns]
    Found 6 outliers among 100 measurements (6.00%)
      2 (2.00%) low mild
      1 (1.00%) high mild
      3 (3.00%) high severe
    
    decode_alternative      time:   [49.407 ns 49.853 ns 50.473 ns]
    Found 5 outliers among 100 measurements (5.00%)
      1 (1.00%) low mild
      1 (1.00%) high mild
      3 (3.00%) high severe

**Comment by ChaiTRex** [comment]
Small behavior change: decoding an empty input will give an error instead of 0 for a few reasons:

* Encoding will never give an empty output                                                                 
* Programmers might not realize that an empty input is an edge case that they might want to handle differently; this notifies them of the edge case
* With, for example, a URL-shortener, `https://what.ever/` should not have the same behavior as `https://what.ever/0`

**Comment by ChaiTRex** [comment]
Encoding is now slightly faster:

    encode_standard_new     time:   [155.10 ns 155.61 ns 156.17 ns]
    
    encode_standard_buf     time:   [160.26 ns 160.95 ns 161.65 ns]
    
    encode_alternative_new  time:   [156.22 ns 156.85 ns 157.44 ns]
    
    encode_alternative_buf  time:   [161.48 ns 163.52 ns 165.91 ns]
    Found 11 outliers among 100 measurements (11.00%)
      2 (2.00%) high mild
      9 (9.00%) high severe

**Comment by ChaiTRex** [comment]
If there are any changes you'd like me to make, please let me know.

**Comment by fbernier** [comment]
Published as 2.0.0

Thanks again!

**Pull request merged**
